// Hand-written, not generated by wxt.
//
// `@emoji-gen/clone-into` ships type declarations at `dist/index.d.ts`, but its
// package.json `exports` map has no `types` condition. Under the `Bundler`
// module resolution wxt configures, TypeScript resolves the module through
// `exports` and so never reaches that file, leaving the import implicitly `any`
// (TS7016). This declaration stands in until the package publishes a `types`
// condition, and mirrors the signature it actually ships.
declare module "@emoji-gen/clone-into" {
  interface CloneIntoOptions {
    cloneFunctions: boolean;
    wrapReflectors: boolean;
  }
  export function cloneInto<T>(
    obj: T,
    targetScope: any,
    options?: CloneIntoOptions
  ): T;
}
